site_name: The jsii reference
site_description: jsii allows code in any language to naturally interact with JavaScript classes.
repo_name: aws/jsii
repo_url: https://github.com/aws/jsii
site_url: https://aws.github.io/jsii/
edit_uri: edit/main/gh-pages/content/
copyright: Copyright &copy; 2021 Amazon Web Services, Inc.

docs_dir: content
extra_css:
  - assets/stylesheets/amazon-ember-display.css
  - assets/stylesheets/extra.css

nav:
  - Welcome:
      - index.md
      - Overview:
          - overview/features.md
          - overview/toolchain.md
          - overview/runtime-architecture.md
      - Maintenance Announcements:
          - jsii@v1.x & jsii-rosetta@v1.x: compiler-and-rosetta-maintenance.md
  - ...

extra:
  social:
    - icon: fontawesome/brands/aws
      name: Amazon Web Services, Inc.
      link: https://aws.amazon.com

theme:
  name: material
  font: false
  logo: assets/images/logo.png
  icon:
    logo: fontawesome/brands/aws
    repo: fontawesome/brands/github
  favicon: assets/images/favicon.png
  palette:
    scheme: default
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tabs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      repo_url_shortener: true
      provider: github
      user: aws
      repo: jsii
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - awesome-pages:
      filename: .pages.yml
  - git-revision-date
  - search
