# Apply various labels on PRs

name: pr-labeler
on:
  pull_request:
    types: [ opened ]

jobs:
  auto-approve:
    if: github.event.pull_request.user.login == 'dependabot[bot]' || github.event.pull_request.user.login == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    permissions:
      actions: write
      issues: write
      pull-requests: write
    steps:
    - run: gh pr edit ${{ github.event.pull_request.number }} --add-label "auto-approve" -R ${{ github.repository }}
      env:
        GITHUB_TOKEN: ${{ secrets.PROJEN_GITHUB_TOKEN }}
